version: '3.6'
services:
  authdb:
    image: postgres:15.6
    volumes:
      - authdb-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD-test}
    ports:
      - '${DB_PORT-5430}:5432'
    restart: always

  auth-backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    image: auth-backend
    ports:
      - '3000:3000'
    depends_on:
      - 'authdb'
    restart: always
    healthcheck:
      test: curl -f http://localhost:3000 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    image: auth-frontend
    ports:
      - '${FRONTEND_PORT-80}:80'
    depends_on:
      - 'auth-backend'
    restart: always
    healthcheck:
      test: curl -f http://localhost:80 || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  authdb-volume: